apiVersion: apps/v1
kind: Deployment
metadata:
  name: shack-deployment-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        home: the-shack
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shack-nginx-service
spec:
  selector:
    app: shack-deployment-nginx
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shack-deployment-redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        home: the-shack
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 80

